module Symbols where
    {-
        → - \to
        ℓ - \ell
        ∀ - \all
        λ - \lambda
        ⊤ - \top
        ⊥ - \bot
        ⊢ - \vdash
        ∧ - \and
        ∨ - \or
        ¬ - \neg
        × - \x
        ⊎ - \uplus
        Σ - \ge
        ℕ - \bN
        ∎ - \qed
        ≡ - \==
        ∸ - \.-
        ⟨ - \<
        ⟩ - \>
        ≤ - \le
        < - \leq
        ≥ - \ge
        > - \geq
        ÷ - \div
        ◂ - \blacktriangleleft
        ▸ - \blacktriangleright
    -}